spring:
  application:
    version: @project.version@
    name: gateway
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 7000
      routes:
        - id: cache-provider-svc
          uri: http://ricci-cache-provider:8083
          predicates:
            - Path=/cache-provider/**
          filters:
            - StripPrefix=1
        - id: message-svc
          uri: http://ricci-message-svc:8082
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
        - id: cache-provider-svc-swagger
          uri: http://ricci-cache-provider:8083
          order: -1
          predicates:
            - Path=/cache-provider/v3/api-docs
          filters:
            - StripPrefix=1
            - name: SpringdocModify
              args:
                enabled: true
        - id: message-svc-swagger
          uri: http://ricci-message-svc:8082
          order: -1
          predicates:
            - Path=/message/v3/api-docs
          filters:
            - StripPrefix=1
            - name: SpringdocModify
              args:
                enabled: true
ricciliao:
  x:
    common:
      time-zone: GMT+8
    log:
      executor:
        enable: true
