spring:
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 7000
      routes:
        - id: cache-provider-svc
          uri: http://ricci-cache-provider:8083
          predicates:
            - Path=/cache-provider/**
          filters:
            - StripPrefix=1
        - id: message-svc
          uri: http://ricci-message-svc:8082
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
        - id: bsm-svc
          uri: http://ricci-bsm-svc:8081
          predicates:
            - Path=/bsm/**
          filters:
            - StripPrefix=1
        - id: cache-provider-svc-swagger
          uri: http://ricci-cache-provider:8083
          order: -1
          predicates:
            - Path=/cache-provider/v3/api-docs
          filters:
            - StripPrefix=1
            - name: SpringdocModify
              args:
                enabled: true
        - id: message-svc-swagger
          uri: http://ricci-message-svc:8082
          order: -1
          predicates:
            - Path=/message/v3/api-docs
          filters:
            - StripPrefix=1
            - name: SpringdocModify
              args:
                enabled: true
        - id: bsm-svc-swagger
          uri: http://ricci-bsm-svc:8081
          order: -1
          predicates:
            - Path=/bsm/v3/api-docs
          filters:
            - StripPrefix=1
            - name: SpringdocModify
              args:
                enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
ricciliao:
  x:
    common:
      time-zone: GMT+8
      consumer: gateway
      version: ${project.version}
    log:
      executor:
        enable: true
